### ISSUE TITLE
Add Line column in the left 

### ISSUE THREAD

**Issue by rahat14** [zehanti/compose-code-editor#7]
Add Line column in the left  like other ide .

**Comment by wakaztahir** [comment]
what do you mean by line column , do you mean numbering , line numbers ?

**Comment by rahat14** [comment]
yes

**Comment by wakaztahir** [comment]
working on it !

**Comment by wakaztahir** [comment]
https://github.com/zehanti/compose-code-editor#displaying-line-numbers
